openapi: 3.1.0
info:
  title: Aplikacja Kurierska
  description: Aplikacja Kurierska
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Address:
      type: object
      required:
        - city
        - postal_code
        - building_no
      properties:
        city:
          type: string
        postal_code:
          type: string
        building_no:
          type: string
        street:
          type: string
        apartment_no:
          type: string
    Shipment:
      type: object
      required:
        - recipientAddress
        - recipientPhone
        - size
      properties:
        id:
          type: string
          format: uuid
        recipientAddress:
          $ref: '#/components/schemas/Address'
        recipientPhone:
          type: string
        size:
          type: string
          enum: [ S, M, L, XL ]
        name:
          type: string
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          $ref: '#/components/schemas/Address'
    PartialUser:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          $ref: '#/components/schemas/Address'
  responses:
    BadToken:
      description: Niepoprawny token lub brak uprawnień do danego zasobu
tags:
  - name: Authentication
  - name: Shipment
  - name: User
paths:
  /api/login:
    post:
      tags:
        - Authentication
      summary: Logowanie i otrzymanie tokena JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: example@example.com
                password: TrudneHaslo

      responses:
        '200':
          description: Pomyślne logowanie
          content:
            text/plain:
              schema:
                type: string
  /api/shipments:
    post:
      tags:
        - Shipment
      summary: Nadanie nowej paczki
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Shipment'
      responses:
        '201':
          description: Paczka została nadana
        '401':
          $ref: '#/components/responses/BadToken'
  /api/shipments/{id}:
    get:
      tags:
        - Shipment
      summary: Szczegóły konkretnej paczki
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          description: Identyfikator paczki
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Szczegóły paczki
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shipment'
        '401':
          $ref: '#/components/responses/BadToken'
  /api/user/@current:
    get:
      tags:
        - User
      summary: Szczegóły obecnie zalogowanego użytkownika
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Dane użytkownika
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/BadToken'
    patch:
      tags:
        - User
      summary: Aktualizacja danych użytkownika
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartialUser'
      responses:
        '200':
          description: Dane zaktualizowane
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/BadToken'
  /api/user/@current/shipments:
    get:
      tags:
        - Shipment
        - User
      summary: Lista paczek użytkownika
      security:
        - bearerAuth: [ ]
      parameters:
        - name: relation
          in: query
          description: Rola użytkownika w stosunku do paczki
          required: false
          schema:
            type: string
            enum: [ sender, recipient ]
            default: sender
      responses:
        '200':
          description: Lista paczek
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shipment'
        '401':
          $ref: '#/components/responses/BadToken'